[package]
name = "rust-tdlib-codegen"
version = "0.1.0"
authors = ["aCLr <a.ch.clr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grammers-tl-parser = "1.0.0"
codegen = "0.1.3"
heck = "0.3.2"
