name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-n-test:

    runs-on: ubuntu-latest

    env:
      API_ID: 1
      API_HASH: 1

    steps:
      - uses: actions/checkout@v2

      - name: formatting
        run: cargo fmt -- --check

      - name: tests
        env:
          RUST_LOG: trace
        run: cargo test --features client

      - name: clippy
        run: cargo clippy --tests --examples --all-features


  build:

    needs:
      - lint-n-test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: cargo build

    - name: build client
      run: cargo build --features client
